{
    'name': "B2B custom",
    'summary': "This is a custom sale module for B2B companies",
    'version': '1.0',
    'category': 'Sales/Sales',
    'depends': ['contacts', 'general_system_custom', 'website_sale', 'mail', 'portal', 'auth_signup'],
    'installable': True,
    'data': [
        'security/baf_b2b_security.xml',
        'security/ir.model.access.csv',
        'data/baf_b2b_signup_config.xml',
        'data/mail_template_baf_b2b.xml',
        'data/product_mass_update_data.xml',
        'data/enable_oos_orders.xml',
        'views/res_partner_b2b_view.xml',
        'views/baf_b2b_apply_template.xml',
        'views/baf_login_template.xml',
        'views/product_template_view.xml',
        'views/website_list_to_part_template.xml',
        'views/website_baf_b2b_template.xml',
        'views/portal_my_home_template.xml',
        'views/website_sale_cart_view.xml',
        'views/website_sale_cart_baf_skin.xml',
        'views/website_backorders_template.xml',
        'views/checkout_template.xml',
        'views/sale_order.xml',
        'views/mass_product_import_view.xml',
        'views/mass_vendor_price_import_view.xml',
        'views/product_mass_update_view.xml',
    ],
    'author': 'Ahmed Elamery',
    'license': 'LGPL-3',
}