{
    'name': "Auto parts Sale",
    'summary': "This is a custom sale module for Auto parts companies",
    'category': 'Sales/Sales',
    'version': '1.0',
    'depends': ['base', 'product', 'sale_management', 'stock', 'sale_stock', 'purchase', 'stock_dropshipping', 'barcodes', 'stock_barcode', 'accountant', 'portal'],
    'installable': True,
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'reports/pallet_label_report.xml',
        'reports/pallet_list_report.xml',
        'reports/invoice_report_axio.xml',
        'reports/corrispettivi_report_views.xml',
        'views/sales_order_line_view.xml',
        'views/purchase_view.xml',
        'views/import_so_lines_view.xml',
        'views/sales_view.xml',
        'views/auto_product_view.xml',
        'views/discount_code_view.xml',
        'views/partner_view.xml',
        'views/dropship_import_view.xml',
        'views/delivery_list_view.xml',
        'views/warehouse_pallet_view.xml',
        'views/warehouse_checking_view.xml',
        'views/account_move_view.xml',
        'views/baf_pricing_views.xml',
        'views/credit_note_wizard_view.xml',
        'views/stock_view.xml',
        'views/down_payment_wizard_view.xml',
        'views/portal_templates.xml',
        'views/discount_import_wizard_view.xml'
    ],
    'assets': {
    'web.assets_backend': [
            'general_system_custom/static/src/js/import_options_patch.js',
            'general_system_custom/static/src/js/barcode_scan_box.js',
            'general_system_custom/static/src/xml/stock_barcode_main_menu.xml',
            'general_system_custom/static/src/xml/barcode_scan_box.xml',
        ],
    },
    'author': 'Ahmed Elamery',
    'license': 'LGPL-3',
}
